// <auto-generated />
using System;
using DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbContexts.AdMigration.Migrations
{
    [DbContext(typeof(AdDbContext))]
    partial class AdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Ad.Entities.Ad", b =>
                {
                    b.Property<long>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiveDays")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(7);

                    b.Property<string>("AdAddressAtPublicSecurityNearLandmarkName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AdAddressCity")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AdAddressDistrictOrCounty")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AdAddressState")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AdAddressStreet")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AdBody")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<string>("AdCountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("AdCountryCurrency")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("AdCountryCurrencyISO_4217")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("AdCountryName")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("AdDescription")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<double>("AdItemsCost");

                    b.Property<string>("AdItemsCostInCurrencyName")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<double>("AdLatitude");

                    b.Property<double>("AdLongitude");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("AdZipCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<DateTime>("ArchivedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("AttachedAssetsInCloudCount");

                    b.Property<Guid?>("AttachedAssetsInCloudStorageId");

                    b.Property<string>("AttachedAssetsStoredInCloudBaseFolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("DeletedDateTime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAdInDraftMode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Tag1")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag10")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag11")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag12")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag2")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag3")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag4")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag5")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag6")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag7")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag8")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag9")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdatedDateTime");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserLoggedInSocialProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserPhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("UserSocialAvatarUrl")
                        .HasMaxLength(2000)
                        .IsUnicode(false);

                    b.HasKey("AdId");

                    b.ToTable("Ad");
                });
#pragma warning restore 612, 618
        }
    }
}
