// <auto-generated />
using System;
using DbContexts.Ad;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbContexts.AdMigration.Migrations
{
    [DbContext(typeof(AdDbContext))]
    partial class AdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Ad.Entities.Ad", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<string>("AdCategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("AdContent")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<int>("AdDisplayDays")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(7);

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("AddressCity")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressCountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("AddressCountryName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressDistrictOrCounty")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<double>("AddressLatitude");

                    b.Property<double>("AddressLongitude");

                    b.Property<string>("AddressPartiesMeetingLandmarkName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressState")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("AddressZipCode")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<int?>("AttachedAssetsInCloudCount");

                    b.Property<Guid?>("AttachedAssetsInCloudStorageId");

                    b.Property<string>("AttachedAssetsStoredInCloudBaseFolderPath")
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("ItemCondition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<double?>("ItemCost");

                    b.Property<string>("ItemCurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<DateTime?>("LastActiveDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastDraftOrBeforePublishedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastInActiveDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("LastPublishedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Tag1")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag2")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag3")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag4")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag5")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag6")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag7")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag8")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag9")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdatedDateTime");

                    b.Property<string>("UserIdOrEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserLoggedInSocialProviderName")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("UserPhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("UserSocialAvatarUrl")
                        .IsUnicode(false);

                    b.HasKey("AdId");

                    b.ToTable("Ad");
                });
#pragma warning restore 612, 618
        }
    }
}
