// <auto-generated />
using System;
using DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbContexts.ArticleMigration.Migrations
{
    [DbContext(typeof(ArticleDbContext))]
    [Migration("20180706213154_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Article.Entities.Article", b =>
                {
                    b.Property<long>("ArticleId");

                    b.Property<string>("AllRelatedSubjectsIncludesVersionsWithComma")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<int>("AttachedAssetsInCloudCount");

                    b.Property<Guid>("AttachedAssetsInCloudStorageId");

                    b.Property<string>("AttachedAssetsStoredInCloudBaseFolderPath")
                        .IsUnicode(false);

                    b.Property<string>("AttachmentURLsComma")
                        .IsUnicode(false);

                    b.Property<string>("BiodataUrl")
                        .IsUnicode(false);

                    b.Property<string>("Body");

                    b.Property<string>("Commits");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("HireMe")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsArticleInDraftMode")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("License");

                    b.Property<string>("OpenSourceUrls")
                        .IsUnicode(false);

                    b.Property<string>("SocialURLsWithComma")
                        .IsUnicode(false);

                    b.Property<string>("Tag1")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag10")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag11")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag12")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag2")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag3")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag4")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag5")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag6")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag7")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag8")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Tag9")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<int?>("TotalVotedPersonsCount");

                    b.Property<int?>("TotalVotes");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserLoggedInSocialProviderName")
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UserPhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("UserSocialAvatarUrl")
                        .IsUnicode(false);

                    b.HasKey("ArticleId");

                    b.ToTable("Article");
                });
#pragma warning restore 612, 618
        }
    }
}
